---
abstract: 'Greps files for pattern'
author:
  - 'Johan Vromans <jv@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-File-Grepper
no_index:
  directory:
    - t
    - inc
requires:
  Encode: 0
  File::Find: 0
  Getopt::Long: 2.13
  Term::ANSIColor: 0
  Test::More: 0
version: 0.06
