--- #YAML:1.0
name:               App-File-Grepper
version:            0.04
abstract:           Greps files for pattern
author:
    - Johan Vromans <jv@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Find:       0
    Getopt::Long:     2.13
    Term::ANSIColor:  0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
